version: "3.7"
services:
  downloader:
    image: alpine:latest
    container_name: downloader
    volumes:
      - data:/data
      - ./download_files.sh:/download_files.sh
    entrypoint: /download_files.sh
    restart: "no"
    command: [ "/bin/sh", "-c", "/download_files.sh && exit 0" ]

  backend:
    build:
      context: ./api
    hostname: api
    restart: always
    container_name: travel_adviser_api
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.cache:/root/.cache/gpt4all
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - downloader
  # frontend:
  #   build:
  #     context: ./ui
  #   hostname: ui
  #   restart: always
  #   container_name: ui
  #   ports:
  #     - 4173:4173
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  networks:
    app-network:
      driver: bridge
