version: "3.7"
services:
  backend:
    build:
      context: ./api
    hostname: api
    restart: always
    container_name: travel_adviser_api
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.cache:/root/.cache/gpt4all
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  # frontend:
  #   build:
  #     context: ./ui
  #   hostname: ui
  #   restart: always
  #   container_name: ui
  #   ports:
  #     - 4173:4173
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  networks:
    app-network:
      driver: bridge
