version: "3.7"
services:
  downloader:
    build:
      context: ./downloader
      dockerfile: Dockerfile
    container_name: downloader
    volumes:
      - ./.cache:/.cache
    restart: "no"

  backend:
    build:
      context: ./api
    hostname: api
    restart: always
    container_name: travel_adviser_api
    expose:
      - "8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./.cache:/root/.cache/gpt4all
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - downloader
    networks:
      - app-network
  # frontend:
  #   build:
  #     context: ./ui
  #   hostname: ui
  #   restart: always
  #   container_name: ui
  #   ports:
  #     - 4173:4173
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
